### ISSUE TITLE
Found incompatible module

### ISSUE THREAD

**Issue by linhtranvu** [eseom/hapi-react-fullstack-boilerplate#5]
I download and cannot make yarn install

`yarn install v1.3.2
[1/5] Validating package.json...
error react-hapi-fullstack-boilerplate@0.1.0: The engine "node" is incompatible with this module. Expected version "8.0.0".
error react-hapi-fullstack-boilerplate@0.1.0: The engine "yarn" is incompatible with this module. Expected version "0.24.5".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.`

My Installed package 's version:

`node: 8.9.1
npm: 5.5.1
yarn: 1.3.2`

So please tell me what I need to do to install

Tks all

**Comment by eseom** [comment]
I figured it out. I have changed the version to be more explicit. :)

**Comment by linhtranvu** [comment]
Tks for help. I could not make it run on Window, try linux and will inform later if fail

**Comment by eseom** [comment]
I'll take a look at it in Windows.
